server:
    port: 6000

kafka:
    bootstrap:
        address: localhost:9092
    schemaregistry:
        address: http://localhost:8081
    consumer:
        topic:
            partner:
                changed: PartnerChanged
            partner:
                deleted: PartnerDeleted
            vertrag:
                created: VertragCreated
            vertrag:
                changed: VertragChanged
            vertrag:
                deleted: VertragDeleted
        group:
            id: vertragGroup
        offset: earliest
    producer:
        topic:
           create:
              vertrag: CreateVertrag
           change:
              vertrag: ChangeVertrag
           delete:
              vertrag: DeleteVertrag