server:
    port: 6000

kafka:
    bootstrap:
        address: localhost:9092
    schemaregistry:
        address: http://localhost:8081
    consumer:
        topic:
            partner:
                changed: PartnerChanged
        group:
            id: vertragGroup
        offset: earliest
    producer:
        topic:
           vertrag:
              created: VertragCreated