server:
    port: ${SERVER_PORT:6000}

kafka:
    bootstrap:
        address: localhost:9092
    schemaregistry:
        address: http://localhost:8081
    consumer:
        topic:
            event:
                client:
                    changed: ClientChanged
                    deleted: ClientDeleted
                    duplicatesfound: ClientDuplicatesFound
                contract:
                    deleted: ContractDeleted
                    delete: DeleteContract
            command:
                contract:
                    delete: DeleteContract

        group:
            id: ${CONSUMER_GROUP_ID:ClientChanged}
        offset: earliest
    producer:
        topic:
            event:
                contract:
                    created: ContractCreated
                    changed: ContractChanged
                    deleted: ContractDeleted
            command:
                contract:
                    delete: DeleteContract