// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen, version 1.7.7.5
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace de.partner.kafkaevent.dubletten
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using global::Avro;
	using global::Avro.Specific;
	
	public partial class PartnerdublettenFound : ISpecificRecord
	{
		public static Schema _SCHEMA = Schema.Parse(@"{""type"":""record"",""name"":""PartnerdublettenFound"",""namespace"":""de.partner.kafkaevent.dubletten"",""fields"":[{""name"":""id"",""type"":""int""},{""name"":""ts"",""type"":""long""},{""name"":""oldpartnerid"",""default"":null,""type"":[""null"",""string""]},{""name"":""newpartnerid"",""default"":null,""type"":[""null"",""string""]}],""connect.name"":""de.partner.dubletten.PartnerdublettenFound""}");
		private int _id;
		private long _ts;
		private string _oldpartnerid;
		private string _newpartnerid;
		public virtual Schema Schema
		{
			get
			{
				return PartnerdublettenFound._SCHEMA;
			}
		}
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				this._id = value;
			}
		}
		public long ts
		{
			get
			{
				return this._ts;
			}
			set
			{
				this._ts = value;
			}
		}
		public string oldpartnerid
		{
			get
			{
				return this._oldpartnerid;
			}
			set
			{
				this._oldpartnerid = value;
			}
		}
		public string newpartnerid
		{
			get
			{
				return this._newpartnerid;
			}
			set
			{
				this._newpartnerid = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.id;
			case 1: return this.ts;
			case 2: return this.oldpartnerid;
			case 3: return this.newpartnerid;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.id = (System.Int32)fieldValue; break;
			case 1: this.ts = (System.Int64)fieldValue; break;
			case 2: this.oldpartnerid = (System.String)fieldValue; break;
			case 3: this.newpartnerid = (System.String)fieldValue; break;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
