version: '3.2'
services:
  elasticsearch:
    image: elasticsearch:5.6.12-alpine
    container_name: elasticsearch
    command: elasticsearch -Ecluster.name=catalog -Ebootstrap.memory_lock=true -Ehttp.port=9200 -Ehttp.cors.allow-origin="http://localhost:1358" -Ehttp.cors.enabled=true -Ehttp.cors.allow-headers=X-Requested-With,X-Auth-Token,Content-Type,Content-Length,Authorization -Ehttp.cors.allow-credentials=true
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
     - "9200:9200"
  dejavu:
    image: appbaseio/dejavu:2.0.5
    container_name: dejavu
    ports:
     - "1358:1358"
    links:
      - elasticsearch

  postgres:
    image: postgres:11.0-alpine
    container_name: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: example
    volumes:
      - ./postgres-default-config/postgresql.conf:/usr/local/share/postgresql/postgresql.conf
      - ./postgres-default-config/CreateDB.sql:/docker-entrypoint-initdb.d/CreateDB.sql

  adminer:
    image: adminer:4.6.3
    container_name: adminer
    restart: always
    ports:
      - 18080:8080
    environment:
      - ADMINER_DEFAULT_SERVER=postgres
      - ADMINER_DESIGN=pepa-linha
    links:
      - postgres

  kafka:
    image: landoop/fast-data-dev:2.0.0
    container_name: kafka
    ports:
      - 2181:2181
      - 3030:3030
      - 8081-8083:8081-8083
      - 9092:9092
    environment:
     - ADV_HOST=${HOSTNAME}
     - SAMPLEDATA=0
