FROM landoop/fast-data-dev:2.0.0
RUN rm /opt/landoop/connectors/third-party/kafka-connect-jdbc/postgresql-9.4-1206-jdbc41.jar
COPY ./postgresql-42.2.5.jar /opt/landoop/connectors/third-party/kafka-connect-jdbc/postgresql-42.2.5.jar
